{ lib }:

{
  build =
    {
      lib,
      site,
      localPool,

      rolesResult ? null,
      roleFromInput ? (if rolesResult != null then rolesResult.roleFromInput else (_: null)),
      nodesBase ? (site.units or site.nodes or { }),
    }:

    let
      addr = import ../../../lib/model/addressing.nix { inherit lib; };

      stripMask =
        cidr:
        let parts = lib.splitString "/" (toString cidr);
        in if builtins.length parts == 0 then toString cidr else builtins.elemAt parts 0;

      allUnits = builtins.attrNames nodesBase;

      coreUnits = lib.filter (u: (roleFromInput u) == "core") allUnits;

      coreUnit =
        if coreUnits == [ ] then
          throw "network-solver: expected at least one unit with role='core'"
        else
          builtins.elemAt (lib.sort (a: b: toString a < toString b) coreUnits) 0;

      upstreamList =
        if site ? upstreams && site.upstreams ? cores
           && site.upstreams.cores ? "${coreUnit}"
        then site.upstreams.cores.${coreUnit}
        else [ ];

      # Use /30 (IPv4) and /126 (IPv6) so the "core" side
      # always gets the first usable address (.1 / ::1).
      # NOTE: The solver does NOT model an upstream peer device.
      mkWanNetBase =
        idx:
        100 + (4 * idx);

      mkWanAddr4 =
        hostIndex:
        let base = "${stripMask localPool.ipv4}/30";
        in addr.hostCidr hostIndex base;

      mkWanAddr6 =
        hostIndex:
        let base = "${stripMask localPool.ipv6}/126";
        in addr.hostCidr hostIndex base;

      mkWanLL6 =
        hostIndex:
        addr.hostCidr (hostIndex + 1) "fe80::/128";

      mkWanLink =
        idx: u:
        let
          nm = if builtins.isAttrs u && u ? name then toString u.name else toString u;

          base = mkWanNetBase idx;

          # .0 = network, .1 = core, .2 = (reserved for peer in other layers), .3 = broadcast
          hCore = base + 1;
        in
        {
          name = "wan-${coreUnit}-${nm}";
          value = {
            kind = "wan";
            carrier = "wan";
            upstream = nm;
            overlay = null;

            # Single-ended WAN link: only the internal core exists in the solver model.
            members = [ coreUnit ];

            endpoints = {
              "${coreUnit}" = {
                gateway = true;
                export = true;

                addr4 = if localPool ? ipv4 then mkWanAddr4 hCore else null;
                addr6 = if localPool ? ipv6 then mkWanAddr6 hCore else null;
                ll6 = mkWanLL6 hCore;

                # IMPORTANT: no peer endpoint is generated by solver.
              };
            };
          };
        };

      wanLinks = lib.listToAttrs (lib.imap0 mkWanLink upstreamList);

    in
    {
      inherit coreUnit wanLinks;
    };
}
